version: '3.1'
services:
  ewm-stats:
    build: ./ewm-stats
    image: ewm-stats-image
    container_name: ewm-stats-dock
    depends_on:
      - ewm-stats-db
    ports:
      - "9090:9090"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-stats-db:5432/ewm-stats
      - SPRING_DATASOURCE_USERNAME=stats
      - SPRING_DATASOURCE_PASSWORD=stats

  ewm-stats-db:
    image: postgres:14-alpine
    ports:
      - "6541:5432"
    container_name: stats-db
    environment:
      - POSTGRES_DB=ewm-stats
      - POSTGRES_USER=stats
      - POSTGRES_PASSWORD=stats



  ewm-service:
    build: ./ewm-main-service
    image: ewm-service-image
    container_name: ewm-service-dock
    ports:
      - "8080:8080"
    depends_on:
      - ewm-service-db
      - ewm-stats
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-service-db:5432/ewm-service
      - SPRING_DATASOURCE_USERNAME=service
      - SPRING_DATASOURCE_PASSWORD=service
      - EWM_STAT_URL=http://ewm-stats:9090

  ewm-service-db:
    image: postgres:14-alpine
    ports:
      - "6540:5432"
    container_name: service-db
    environment:
      - POSTGRES_DB=ewm-service
      - POSTGRES_USER=service
      - POSTGRES_PASSWORD=service