CREATE TABLE IF NOT EXISTS stats
(
    endpoint_hits_id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    app      VARCHAR(256),
    uri      VARCHAR(256),
    ip       VARCHAR(50),
    req_time TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_stat PRIMARY KEY (endpoint_hits_id)
);